services:
  # --------------------------------------------------------------------------------
  # 1. API Service
  # --------------------------------------------------------------------------------
  - type: web
    name: postificus-api
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    numInstances: 1
    dockerCommand: ./postificus-api
    envVars:
      - key: APP_ENV
        value: production
      - key: DEFAULT_USER_ID
        value: "00000000-0000-0000-0000-000000000001"
      - key: WORKER_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_BUCKET
        value: postificus-uploads
      - key: S3_PUBLIC_URL
        sync: false

  # --------------------------------------------------------------------------------
  # 2. Worker Service
  # --------------------------------------------------------------------------------
  - type: web
    name: postificus-worker
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    numInstances: 1
    dockerCommand: ./postificus-worker
    envVars:
      - key: APP_ENV
        value: production
      - key: DEFAULT_USER_ID
        value: "00000000-0000-0000-0000-000000000001"
      - key: BROWSER_HEADLESS
        value: "true"
      - key: BROWSER_BIN
        value: /usr/bin/chromium-browser
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_BUCKET
        value: postificus-uploads
      - key: S3_PUBLIC_URL
        sync: false
